# Generated by Django 5.2.15 on 2026-06-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='category',
            field=models.CharField(choices=[('Performance', 'Performance'), ('Workshop', 'Workshop'), ('Competition', 'Competition'), ('Arangetram', 'Arangetram'), ('Event', 'Event'), ('Award', 'Award')], default='Performance', max_length=20),
            preserve_default=False,
        ),
    ]
