# Generated by Django 5.2.15 on 2026-06-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_gallery_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='category',
            field=models.CharField(choices=[('Performance', 'Performance'), ('Workshop', 'Workshop'), ('Competition', 'Competition'), ('Arangetram', 'Arangetram'), ('Event', 'Event'), ('Award', 'Award')], default='Performance', max_length=20),
        ),
    ]
