# Generated by Django 5.2.15 on 2026-06-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('parent_name', models.CharField(blank=True, max_length=100)),
                ('age', models.IntegerField()),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('course', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True)),
                ('submitted_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
